### ISSUE TITLE
Question about Ziggurat place and boss and potion bag and ore gen

### ISSUE THREAD

**Issue by KamiSami** [pale-imitations/Magic_Kingdoms#15]
Hi, so i looked the video about of this place and went there on adventure, sacrificed chicken as that was needed, defeated Ziggurat, but im not able to mine anything at all in there even after defeating him... Is this bug or intended? I can't craft or do anything with the demon heart i got at least so if that was the reward, what can i do with it exactly?

**Comment by KamiSami** [comment]
Also tome of diabolism shows blank leather covers only when opened, having no pages or anything, is this just not yet done?

**Comment by KamiSami** [comment]
I am getting internal server error when i try open potion bag wheel, should i send logs or if this happens to you aswell it might be easier you to track it down? Or is this not implemented to work yet? (Wonders)

**Comment by KamiSami** [comment]
And one more question... At what height does copper and other ores from this mod generate in? Or do they generate in certain biomes? I am not seeing any of the ores from this mod just yet when i went to look around in my world in creative..

**Comment by pale-imitations** [comment]
1) The Ziggurat did have a pretty major error with the curse not breaking but I just did a bugfix on that and it should be good in 1.2.5
2) The Tomes of Diabolism, Infernality, Mycelimancy, and Chronomancy are all currently empty purely because they just don't have spells yet, none of the tomes are complete and I have at least another 120 spells planned and only 80 currently implemented.
3) The Demonic heart is used in a Ritual which was described in the Mal Occultum, however, that book is currently a WIP and not ready to be released. You place the heart on top of a block of Runic Gold and do a series of commands that activate the heart creating your own area of blocks that are unbreakable to everyone but the caster. The commands are /chant dortan, /chant dortan, /bellow umbriez, /chant qitere, /shriek nunca, /chant altera, /chant miharmai, /chant hearth
4) I'll check out the potion bag, but it would definitely help to see the log
5) Copper is supposed to generate between 10-50 and its pretty rare

**Comment by pale-imitations** [comment]
I apologize for the slow responses, I'm typically on the MK discord server though if you ever need quicker responses
